// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Moritz Voss

// <auto-generated by csharp/tools/generate-structured.mjs />
#nullable enable
using tweens.gd;

namespace Tweens;

/// <summary>Reusable immutable SpriteBase3DModulate configuration. Each start creates independent playback.</summary>
public readonly record struct SpriteBase3DModulate : ITweenDefinition<Godot.SpriteBase3D, Godot.Color>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Color? From { get; init; }
    public Godot.Color? To { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, Godot.Color>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, Godot.Color>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, Godot.Color>, Godot.Color>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, Godot.Color>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, Godot.Color>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, Godot.Color>>? OnFinally { get; init; }

    TweenDefinition<Godot.SpriteBase3D, Godot.Color> ITweenDefinition<Godot.SpriteBase3D, Godot.Color>.CreatePlayback()
    {
        var playback = new tweens.gd.SpriteBase3DModulateTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable SpriteBase3DModulateAlpha configuration. Each start creates independent playback.</summary>
public readonly record struct SpriteBase3DModulateAlpha : ITweenDefinition<Godot.SpriteBase3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.SpriteBase3D, float> ITweenDefinition<Godot.SpriteBase3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.SpriteBase3DModulateAlphaTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable SpriteBase3DOffset configuration. Each start creates independent playback.</summary>
public readonly record struct SpriteBase3DOffset : ITweenDefinition<Godot.SpriteBase3D, Godot.Vector2>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Vector2? From { get; init; }
    public Godot.Vector2? To { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, Godot.Vector2>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, Godot.Vector2>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, Godot.Vector2>, Godot.Vector2>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, Godot.Vector2>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, Godot.Vector2>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, Godot.Vector2>>? OnFinally { get; init; }

    TweenDefinition<Godot.SpriteBase3D, Godot.Vector2> ITweenDefinition<Godot.SpriteBase3D, Godot.Vector2>.CreatePlayback()
    {
        var playback = new tweens.gd.SpriteBase3DOffsetTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable SpriteBase3DOffsetX configuration. Each start creates independent playback.</summary>
public readonly record struct SpriteBase3DOffsetX : ITweenDefinition<Godot.SpriteBase3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.SpriteBase3D, float> ITweenDefinition<Godot.SpriteBase3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.SpriteBase3DOffsetXTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable SpriteBase3DOffsetY configuration. Each start creates independent playback.</summary>
public readonly record struct SpriteBase3DOffsetY : ITweenDefinition<Godot.SpriteBase3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.SpriteBase3D, float> ITweenDefinition<Godot.SpriteBase3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.SpriteBase3DOffsetYTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable SpriteBase3DPixelSize configuration. Each start creates independent playback.</summary>
public readonly record struct SpriteBase3DPixelSize : ITweenDefinition<Godot.SpriteBase3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.SpriteBase3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.SpriteBase3D, float> ITweenDefinition<Godot.SpriteBase3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.SpriteBase3DPixelSizeTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Label3DModulate configuration. Each start creates independent playback.</summary>
public readonly record struct Label3DModulate : ITweenDefinition<Godot.Label3D, Godot.Color>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Color? From { get; init; }
    public Godot.Color? To { get; init; }
    public Action<TweenInstance<Godot.Label3D, Godot.Color>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Label3D, Godot.Color>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Label3D, Godot.Color>, Godot.Color>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Label3D, Godot.Color>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Label3D, Godot.Color>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Label3D, Godot.Color>>? OnFinally { get; init; }

    TweenDefinition<Godot.Label3D, Godot.Color> ITweenDefinition<Godot.Label3D, Godot.Color>.CreatePlayback()
    {
        var playback = new tweens.gd.Label3DModulateTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Label3DModulateAlpha configuration. Each start creates independent playback.</summary>
public readonly record struct Label3DModulateAlpha : ITweenDefinition<Godot.Label3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Label3D, float> ITweenDefinition<Godot.Label3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Label3DModulateAlphaTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Label3DOutlineModulate configuration. Each start creates independent playback.</summary>
public readonly record struct Label3DOutlineModulate : ITweenDefinition<Godot.Label3D, Godot.Color>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Color? From { get; init; }
    public Godot.Color? To { get; init; }
    public Action<TweenInstance<Godot.Label3D, Godot.Color>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Label3D, Godot.Color>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Label3D, Godot.Color>, Godot.Color>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Label3D, Godot.Color>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Label3D, Godot.Color>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Label3D, Godot.Color>>? OnFinally { get; init; }

    TweenDefinition<Godot.Label3D, Godot.Color> ITweenDefinition<Godot.Label3D, Godot.Color>.CreatePlayback()
    {
        var playback = new tweens.gd.Label3DOutlineModulateTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Label3DOutlineModulateAlpha configuration. Each start creates independent playback.</summary>
public readonly record struct Label3DOutlineModulateAlpha : ITweenDefinition<Godot.Label3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Label3D, float> ITweenDefinition<Godot.Label3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Label3DOutlineModulateAlphaTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Label3DOffset configuration. Each start creates independent playback.</summary>
public readonly record struct Label3DOffset : ITweenDefinition<Godot.Label3D, Godot.Vector2>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Vector2? From { get; init; }
    public Godot.Vector2? To { get; init; }
    public Action<TweenInstance<Godot.Label3D, Godot.Vector2>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Label3D, Godot.Vector2>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Label3D, Godot.Vector2>, Godot.Vector2>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Label3D, Godot.Vector2>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Label3D, Godot.Vector2>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Label3D, Godot.Vector2>>? OnFinally { get; init; }

    TweenDefinition<Godot.Label3D, Godot.Vector2> ITweenDefinition<Godot.Label3D, Godot.Vector2>.CreatePlayback()
    {
        var playback = new tweens.gd.Label3DOffsetTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Label3DOffsetX configuration. Each start creates independent playback.</summary>
public readonly record struct Label3DOffsetX : ITweenDefinition<Godot.Label3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Label3D, float> ITweenDefinition<Godot.Label3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Label3DOffsetXTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Label3DOffsetY configuration. Each start creates independent playback.</summary>
public readonly record struct Label3DOffsetY : ITweenDefinition<Godot.Label3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Label3D, float> ITweenDefinition<Godot.Label3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Label3DOffsetYTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Label3DPixelSize configuration. Each start creates independent playback.</summary>
public readonly record struct Label3DPixelSize : ITweenDefinition<Godot.Label3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Label3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Label3D, float> ITweenDefinition<Godot.Label3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Label3DPixelSizeTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable GeometryInstance3DTransparency configuration. Each start creates independent playback.</summary>
public readonly record struct GeometryInstance3DTransparency : ITweenDefinition<Godot.GeometryInstance3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.GeometryInstance3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.GeometryInstance3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.GeometryInstance3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.GeometryInstance3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.GeometryInstance3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.GeometryInstance3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.GeometryInstance3D, float> ITweenDefinition<Godot.GeometryInstance3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.GeometryInstance3DTransparencyTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}
