// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Moritz Voss

// <auto-generated by csharp/tools/generate-structured.mjs />
#nullable enable
using tweens.gd;

namespace Tweens;

/// <summary>Reusable immutable AudioVolumeDb configuration. Each start creates independent playback.</summary>
public readonly record struct AudioVolumeDb : ITweenDefinition<Godot.AudioStreamPlayer, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.AudioStreamPlayer, float> ITweenDefinition<Godot.AudioStreamPlayer, float>.CreatePlayback()
    {
        var playback = new tweens.gd.AudioVolumeDbTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable AudioVolumeLinear configuration. Each start creates independent playback.</summary>
public readonly record struct AudioVolumeLinear : ITweenDefinition<Godot.AudioStreamPlayer, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.AudioStreamPlayer, float> ITweenDefinition<Godot.AudioStreamPlayer, float>.CreatePlayback()
    {
        var playback = new tweens.gd.AudioVolumeLinearTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable AudioPitchScale configuration. Each start creates independent playback.</summary>
public readonly record struct AudioPitchScale : ITweenDefinition<Godot.AudioStreamPlayer, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.AudioStreamPlayer, float> ITweenDefinition<Godot.AudioStreamPlayer, float>.CreatePlayback()
    {
        var playback = new tweens.gd.AudioPitchScaleTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable AudioVolumeDb2D configuration. Each start creates independent playback.</summary>
public readonly record struct AudioVolumeDb2D : ITweenDefinition<Godot.AudioStreamPlayer2D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.AudioStreamPlayer2D, float> ITweenDefinition<Godot.AudioStreamPlayer2D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.AudioVolumeDb2DTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable AudioVolumeLinear2D configuration. Each start creates independent playback.</summary>
public readonly record struct AudioVolumeLinear2D : ITweenDefinition<Godot.AudioStreamPlayer2D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.AudioStreamPlayer2D, float> ITweenDefinition<Godot.AudioStreamPlayer2D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.AudioVolumeLinear2DTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable AudioPitchScale2D configuration. Each start creates independent playback.</summary>
public readonly record struct AudioPitchScale2D : ITweenDefinition<Godot.AudioStreamPlayer2D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.AudioStreamPlayer2D, float> ITweenDefinition<Godot.AudioStreamPlayer2D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.AudioPitchScale2DTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable AudioVolumeDb3D configuration. Each start creates independent playback.</summary>
public readonly record struct AudioVolumeDb3D : ITweenDefinition<Godot.AudioStreamPlayer3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.AudioStreamPlayer3D, float> ITweenDefinition<Godot.AudioStreamPlayer3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.AudioVolumeDb3DTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable AudioVolumeLinear3D configuration. Each start creates independent playback.</summary>
public readonly record struct AudioVolumeLinear3D : ITweenDefinition<Godot.AudioStreamPlayer3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.AudioStreamPlayer3D, float> ITweenDefinition<Godot.AudioStreamPlayer3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.AudioVolumeLinear3DTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable AudioPitchScale3D configuration. Each start creates independent playback.</summary>
public readonly record struct AudioPitchScale3D : ITweenDefinition<Godot.AudioStreamPlayer3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.AudioStreamPlayer3D, float> ITweenDefinition<Godot.AudioStreamPlayer3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.AudioPitchScale3DTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}
