// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Moritz Voss

// <auto-generated by csharp/tools/generate-structured.mjs />
#nullable enable
using tweens.gd;

namespace Tweens;

/// <summary>Reusable immutable Camera2DZoom configuration. Each start creates independent playback.</summary>
public readonly record struct Camera2DZoom : ITweenDefinition<Godot.Camera2D, Godot.Vector2>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Vector2? From { get; init; }
    public Godot.Vector2? To { get; init; }
    public Action<TweenInstance<Godot.Camera2D, Godot.Vector2>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Camera2D, Godot.Vector2>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Camera2D, Godot.Vector2>, Godot.Vector2>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Camera2D, Godot.Vector2>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Camera2D, Godot.Vector2>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Camera2D, Godot.Vector2>>? OnFinally { get; init; }

    TweenDefinition<Godot.Camera2D, Godot.Vector2> ITweenDefinition<Godot.Camera2D, Godot.Vector2>.CreatePlayback()
    {
        var playback = new tweens.gd.Camera2DZoomTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Camera2DZoomX configuration. Each start creates independent playback.</summary>
public readonly record struct Camera2DZoomX : ITweenDefinition<Godot.Camera2D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Camera2D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Camera2D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Camera2D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Camera2D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Camera2D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Camera2D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Camera2D, float> ITweenDefinition<Godot.Camera2D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Camera2DZoomXTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Camera2DZoomY configuration. Each start creates independent playback.</summary>
public readonly record struct Camera2DZoomY : ITweenDefinition<Godot.Camera2D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Camera2D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Camera2D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Camera2D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Camera2D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Camera2D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Camera2D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Camera2D, float> ITweenDefinition<Godot.Camera2D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Camera2DZoomYTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Camera2DOffset configuration. Each start creates independent playback.</summary>
public readonly record struct Camera2DOffset : ITweenDefinition<Godot.Camera2D, Godot.Vector2>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Vector2? From { get; init; }
    public Godot.Vector2? To { get; init; }
    public Action<TweenInstance<Godot.Camera2D, Godot.Vector2>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Camera2D, Godot.Vector2>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Camera2D, Godot.Vector2>, Godot.Vector2>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Camera2D, Godot.Vector2>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Camera2D, Godot.Vector2>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Camera2D, Godot.Vector2>>? OnFinally { get; init; }

    TweenDefinition<Godot.Camera2D, Godot.Vector2> ITweenDefinition<Godot.Camera2D, Godot.Vector2>.CreatePlayback()
    {
        var playback = new tweens.gd.Camera2DOffsetTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Camera2DOffsetX configuration. Each start creates independent playback.</summary>
public readonly record struct Camera2DOffsetX : ITweenDefinition<Godot.Camera2D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Camera2D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Camera2D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Camera2D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Camera2D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Camera2D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Camera2D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Camera2D, float> ITweenDefinition<Godot.Camera2D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Camera2DOffsetXTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Camera2DOffsetY configuration. Each start creates independent playback.</summary>
public readonly record struct Camera2DOffsetY : ITweenDefinition<Godot.Camera2D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Camera2D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Camera2D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Camera2D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Camera2D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Camera2D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Camera2D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Camera2D, float> ITweenDefinition<Godot.Camera2D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Camera2DOffsetYTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Camera3DFov configuration. Each start creates independent playback.</summary>
public readonly record struct Camera3DFov : ITweenDefinition<Godot.Camera3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Camera3D, float> ITweenDefinition<Godot.Camera3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Camera3DFovTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Camera3DSize configuration. Each start creates independent playback.</summary>
public readonly record struct Camera3DSize : ITweenDefinition<Godot.Camera3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Camera3D, float> ITweenDefinition<Godot.Camera3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Camera3DSizeTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Camera3DHOffset configuration. Each start creates independent playback.</summary>
public readonly record struct Camera3DHOffset : ITweenDefinition<Godot.Camera3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Camera3D, float> ITweenDefinition<Godot.Camera3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Camera3DHOffsetTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Camera3DVOffset configuration. Each start creates independent playback.</summary>
public readonly record struct Camera3DVOffset : ITweenDefinition<Godot.Camera3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Camera3D, float> ITweenDefinition<Godot.Camera3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Camera3DVOffsetTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Camera3DNear configuration. Each start creates independent playback.</summary>
public readonly record struct Camera3DNear : ITweenDefinition<Godot.Camera3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Camera3D, float> ITweenDefinition<Godot.Camera3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Camera3DNearTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Camera3DFar configuration. Each start creates independent playback.</summary>
public readonly record struct Camera3DFar : ITweenDefinition<Godot.Camera3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Camera3D, float> ITweenDefinition<Godot.Camera3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Camera3DFarTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Camera3DFrustumOffset configuration. Each start creates independent playback.</summary>
public readonly record struct Camera3DFrustumOffset : ITweenDefinition<Godot.Camera3D, Godot.Vector2>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Vector2? From { get; init; }
    public Godot.Vector2? To { get; init; }
    public Action<TweenInstance<Godot.Camera3D, Godot.Vector2>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Camera3D, Godot.Vector2>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Camera3D, Godot.Vector2>, Godot.Vector2>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Camera3D, Godot.Vector2>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Camera3D, Godot.Vector2>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Camera3D, Godot.Vector2>>? OnFinally { get; init; }

    TweenDefinition<Godot.Camera3D, Godot.Vector2> ITweenDefinition<Godot.Camera3D, Godot.Vector2>.CreatePlayback()
    {
        var playback = new tweens.gd.Camera3DFrustumOffsetTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Camera3DFrustumOffsetX configuration. Each start creates independent playback.</summary>
public readonly record struct Camera3DFrustumOffsetX : ITweenDefinition<Godot.Camera3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Camera3D, float> ITweenDefinition<Godot.Camera3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Camera3DFrustumOffsetXTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Camera3DFrustumOffsetY configuration. Each start creates independent playback.</summary>
public readonly record struct Camera3DFrustumOffsetY : ITweenDefinition<Godot.Camera3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Camera3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Camera3D, float> ITweenDefinition<Godot.Camera3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Camera3DFrustumOffsetYTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}
