// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Moritz Voss

// <auto-generated by csharp/tools/generate-structured.mjs />
#nullable enable
using tweens.gd;

namespace Tweens;

/// <summary>Reusable immutable Modulate configuration. Each start creates independent playback.</summary>
public readonly record struct Modulate : ITweenDefinition<Godot.CanvasItem, Godot.Color>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Color? From { get; init; }
    public Godot.Color? To { get; init; }
    public Action<TweenInstance<Godot.CanvasItem, Godot.Color>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.CanvasItem, Godot.Color>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.CanvasItem, Godot.Color>, Godot.Color>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.CanvasItem, Godot.Color>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.CanvasItem, Godot.Color>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.CanvasItem, Godot.Color>>? OnFinally { get; init; }

    TweenDefinition<Godot.CanvasItem, Godot.Color> ITweenDefinition<Godot.CanvasItem, Godot.Color>.CreatePlayback()
    {
        var playback = new tweens.gd.ModulateTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable ModulateAlpha configuration. Each start creates independent playback.</summary>
public readonly record struct ModulateAlpha : ITweenDefinition<Godot.CanvasItem, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.CanvasItem, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.CanvasItem, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.CanvasItem, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.CanvasItem, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.CanvasItem, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.CanvasItem, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.CanvasItem, float> ITweenDefinition<Godot.CanvasItem, float>.CreatePlayback()
    {
        var playback = new tweens.gd.ModulateAlphaTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable SelfModulate configuration. Each start creates independent playback.</summary>
public readonly record struct SelfModulate : ITweenDefinition<Godot.CanvasItem, Godot.Color>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Color? From { get; init; }
    public Godot.Color? To { get; init; }
    public Action<TweenInstance<Godot.CanvasItem, Godot.Color>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.CanvasItem, Godot.Color>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.CanvasItem, Godot.Color>, Godot.Color>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.CanvasItem, Godot.Color>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.CanvasItem, Godot.Color>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.CanvasItem, Godot.Color>>? OnFinally { get; init; }

    TweenDefinition<Godot.CanvasItem, Godot.Color> ITweenDefinition<Godot.CanvasItem, Godot.Color>.CreatePlayback()
    {
        var playback = new tweens.gd.SelfModulateTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable SelfModulateAlpha configuration. Each start creates independent playback.</summary>
public readonly record struct SelfModulateAlpha : ITweenDefinition<Godot.CanvasItem, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.CanvasItem, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.CanvasItem, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.CanvasItem, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.CanvasItem, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.CanvasItem, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.CanvasItem, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.CanvasItem, float> ITweenDefinition<Godot.CanvasItem, float>.CreatePlayback()
    {
        var playback = new tweens.gd.SelfModulateAlphaTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}
