// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Moritz Voss

// <auto-generated by csharp/tools/generate-structured.mjs />
#nullable enable
using tweens.gd;

namespace Tweens;

/// <summary>Reusable immutable ControlPosition configuration. Each start creates independent playback.</summary>
public readonly record struct ControlPosition : ITweenDefinition<Godot.Control, Godot.Vector2>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Vector2? From { get; init; }
    public Godot.Vector2? To { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>, Godot.Vector2>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnFinally { get; init; }

    TweenDefinition<Godot.Control, Godot.Vector2> ITweenDefinition<Godot.Control, Godot.Vector2>.CreatePlayback()
    {
        var playback = new tweens.gd.ControlPositionTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable ControlPositionX configuration. Each start creates independent playback.</summary>
public readonly record struct ControlPositionX : ITweenDefinition<Godot.Control, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Control, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Control, float> ITweenDefinition<Godot.Control, float>.CreatePlayback()
    {
        var playback = new tweens.gd.ControlPositionXTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable ControlPositionY configuration. Each start creates independent playback.</summary>
public readonly record struct ControlPositionY : ITweenDefinition<Godot.Control, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Control, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Control, float> ITweenDefinition<Godot.Control, float>.CreatePlayback()
    {
        var playback = new tweens.gd.ControlPositionYTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable ControlGlobalPosition configuration. Each start creates independent playback.</summary>
public readonly record struct ControlGlobalPosition : ITweenDefinition<Godot.Control, Godot.Vector2>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Vector2? From { get; init; }
    public Godot.Vector2? To { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>, Godot.Vector2>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnFinally { get; init; }

    TweenDefinition<Godot.Control, Godot.Vector2> ITweenDefinition<Godot.Control, Godot.Vector2>.CreatePlayback()
    {
        var playback = new tweens.gd.ControlGlobalPositionTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable ControlGlobalPositionX configuration. Each start creates independent playback.</summary>
public readonly record struct ControlGlobalPositionX : ITweenDefinition<Godot.Control, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Control, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Control, float> ITweenDefinition<Godot.Control, float>.CreatePlayback()
    {
        var playback = new tweens.gd.ControlGlobalPositionXTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable ControlGlobalPositionY configuration. Each start creates independent playback.</summary>
public readonly record struct ControlGlobalPositionY : ITweenDefinition<Godot.Control, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Control, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Control, float> ITweenDefinition<Godot.Control, float>.CreatePlayback()
    {
        var playback = new tweens.gd.ControlGlobalPositionYTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable ControlSize configuration. Each start creates independent playback.</summary>
public readonly record struct ControlSize : ITweenDefinition<Godot.Control, Godot.Vector2>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Vector2? From { get; init; }
    public Godot.Vector2? To { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>, Godot.Vector2>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnFinally { get; init; }

    TweenDefinition<Godot.Control, Godot.Vector2> ITweenDefinition<Godot.Control, Godot.Vector2>.CreatePlayback()
    {
        var playback = new tweens.gd.ControlSizeTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable ControlSizeX configuration. Each start creates independent playback.</summary>
public readonly record struct ControlSizeX : ITweenDefinition<Godot.Control, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Control, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Control, float> ITweenDefinition<Godot.Control, float>.CreatePlayback()
    {
        var playback = new tweens.gd.ControlSizeXTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable ControlSizeY configuration. Each start creates independent playback.</summary>
public readonly record struct ControlSizeY : ITweenDefinition<Godot.Control, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Control, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Control, float> ITweenDefinition<Godot.Control, float>.CreatePlayback()
    {
        var playback = new tweens.gd.ControlSizeYTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable ControlScale configuration. Each start creates independent playback.</summary>
public readonly record struct ControlScale : ITweenDefinition<Godot.Control, Godot.Vector2>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Vector2? From { get; init; }
    public Godot.Vector2? To { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>, Godot.Vector2>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnFinally { get; init; }

    TweenDefinition<Godot.Control, Godot.Vector2> ITweenDefinition<Godot.Control, Godot.Vector2>.CreatePlayback()
    {
        var playback = new tweens.gd.ControlScaleTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable ControlScaleX configuration. Each start creates independent playback.</summary>
public readonly record struct ControlScaleX : ITweenDefinition<Godot.Control, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Control, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Control, float> ITweenDefinition<Godot.Control, float>.CreatePlayback()
    {
        var playback = new tweens.gd.ControlScaleXTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable ControlScaleY configuration. Each start creates independent playback.</summary>
public readonly record struct ControlScaleY : ITweenDefinition<Godot.Control, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Control, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Control, float> ITweenDefinition<Godot.Control, float>.CreatePlayback()
    {
        var playback = new tweens.gd.ControlScaleYTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable ControlRotation configuration. Each start creates independent playback.</summary>
public readonly record struct ControlRotation : ITweenDefinition<Godot.Control, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Control, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Control, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Control, float> ITweenDefinition<Godot.Control, float>.CreatePlayback()
    {
        var playback = new tweens.gd.ControlRotationTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable RangeValue configuration. Each start creates independent playback.</summary>
public readonly record struct RangeValue : ITweenDefinition<Godot.Range, double>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public double? From { get; init; }
    public double? To { get; init; }
    public Action<TweenInstance<Godot.Range, double>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Range, double>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Range, double>, double>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Range, double>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Range, double>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Range, double>>? OnFinally { get; init; }

    TweenDefinition<Godot.Range, double> ITweenDefinition<Godot.Range, double>.CreatePlayback()
    {
        var playback = new tweens.gd.RangeValueTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable ControlAnchorMin configuration. Each start creates independent playback.</summary>
public readonly record struct ControlAnchorMin : ITweenDefinition<Godot.Control, Godot.Vector2>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Vector2? From { get; init; }
    public Godot.Vector2? To { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>, Godot.Vector2>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnFinally { get; init; }

    TweenDefinition<Godot.Control, Godot.Vector2> ITweenDefinition<Godot.Control, Godot.Vector2>.CreatePlayback()
    {
        var playback = new tweens.gd.ControlAnchorMinTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable ControlAnchorMax configuration. Each start creates independent playback.</summary>
public readonly record struct ControlAnchorMax : ITweenDefinition<Godot.Control, Godot.Vector2>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Vector2? From { get; init; }
    public Godot.Vector2? To { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>, Godot.Vector2>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector2>>? OnFinally { get; init; }

    TweenDefinition<Godot.Control, Godot.Vector2> ITweenDefinition<Godot.Control, Godot.Vector2>.CreatePlayback()
    {
        var playback = new tweens.gd.ControlAnchorMaxTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable ControlOffsets configuration. Each start creates independent playback.</summary>
public readonly record struct ControlOffsets : ITweenDefinition<Godot.Control, Godot.Vector4>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Vector4? From { get; init; }
    public Godot.Vector4? To { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector4>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector4>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector4>, Godot.Vector4>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector4>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector4>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Control, Godot.Vector4>>? OnFinally { get; init; }

    TweenDefinition<Godot.Control, Godot.Vector4> ITweenDefinition<Godot.Control, Godot.Vector4>.CreatePlayback()
    {
        var playback = new tweens.gd.ControlOffsetsTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}
