// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Moritz Voss

// <auto-generated by csharp/tools/generate-structured.mjs />
#nullable enable
using tweens.gd;

namespace Tweens;

/// <summary>Reusable immutable LabelVisibleCharacters configuration. Each start creates independent playback.</summary>
public readonly record struct LabelVisibleCharacters : ITweenDefinition<Godot.Label, int>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public int? From { get; init; }
    public int? To { get; init; }
    public Action<TweenInstance<Godot.Label, int>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Label, int>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Label, int>, int>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Label, int>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Label, int>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Label, int>>? OnFinally { get; init; }

    TweenDefinition<Godot.Label, int> ITweenDefinition<Godot.Label, int>.CreatePlayback()
    {
        var playback = new tweens.gd.LabelVisibleCharactersTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable RichTextLabelVisibleCharacters configuration. Each start creates independent playback.</summary>
public readonly record struct RichTextLabelVisibleCharacters : ITweenDefinition<Godot.RichTextLabel, int>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public int? From { get; init; }
    public int? To { get; init; }
    public Action<TweenInstance<Godot.RichTextLabel, int>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.RichTextLabel, int>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.RichTextLabel, int>, int>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.RichTextLabel, int>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.RichTextLabel, int>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.RichTextLabel, int>>? OnFinally { get; init; }

    TweenDefinition<Godot.RichTextLabel, int> ITweenDefinition<Godot.RichTextLabel, int>.CreatePlayback()
    {
        var playback = new tweens.gd.RichTextLabelVisibleCharactersTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable ScrollContainerScrollHorizontal configuration. Each start creates independent playback.</summary>
public readonly record struct ScrollContainerScrollHorizontal : ITweenDefinition<Godot.ScrollContainer, int>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public int? From { get; init; }
    public int? To { get; init; }
    public Action<TweenInstance<Godot.ScrollContainer, int>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.ScrollContainer, int>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.ScrollContainer, int>, int>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.ScrollContainer, int>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.ScrollContainer, int>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.ScrollContainer, int>>? OnFinally { get; init; }

    TweenDefinition<Godot.ScrollContainer, int> ITweenDefinition<Godot.ScrollContainer, int>.CreatePlayback()
    {
        var playback = new tweens.gd.ScrollContainerScrollHorizontalTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable ScrollContainerScrollVertical configuration. Each start creates independent playback.</summary>
public readonly record struct ScrollContainerScrollVertical : ITweenDefinition<Godot.ScrollContainer, int>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public int? From { get; init; }
    public int? To { get; init; }
    public Action<TweenInstance<Godot.ScrollContainer, int>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.ScrollContainer, int>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.ScrollContainer, int>, int>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.ScrollContainer, int>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.ScrollContainer, int>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.ScrollContainer, int>>? OnFinally { get; init; }

    TweenDefinition<Godot.ScrollContainer, int> ITweenDefinition<Godot.ScrollContainer, int>.CreatePlayback()
    {
        var playback = new tweens.gd.ScrollContainerScrollVerticalTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Sprite2DFrame configuration. Each start creates independent playback.</summary>
public readonly record struct Sprite2DFrame : ITweenDefinition<Godot.Sprite2D, int>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public int? From { get; init; }
    public int? To { get; init; }
    public Action<TweenInstance<Godot.Sprite2D, int>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Sprite2D, int>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Sprite2D, int>, int>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Sprite2D, int>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Sprite2D, int>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Sprite2D, int>>? OnFinally { get; init; }

    TweenDefinition<Godot.Sprite2D, int> ITweenDefinition<Godot.Sprite2D, int>.CreatePlayback()
    {
        var playback = new tweens.gd.Sprite2DFrameTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable AnimatedSprite2DFrame configuration. Each start creates independent playback.</summary>
public readonly record struct AnimatedSprite2DFrame : ITweenDefinition<Godot.AnimatedSprite2D, int>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public int? From { get; init; }
    public int? To { get; init; }
    public Action<TweenInstance<Godot.AnimatedSprite2D, int>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.AnimatedSprite2D, int>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.AnimatedSprite2D, int>, int>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.AnimatedSprite2D, int>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.AnimatedSprite2D, int>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.AnimatedSprite2D, int>>? OnFinally { get; init; }

    TweenDefinition<Godot.AnimatedSprite2D, int> ITweenDefinition<Godot.AnimatedSprite2D, int>.CreatePlayback()
    {
        var playback = new tweens.gd.AnimatedSprite2DFrameTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable AnimatedSprite3DFrame configuration. Each start creates independent playback.</summary>
public readonly record struct AnimatedSprite3DFrame : ITweenDefinition<Godot.AnimatedSprite3D, int>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public int? From { get; init; }
    public int? To { get; init; }
    public Action<TweenInstance<Godot.AnimatedSprite3D, int>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.AnimatedSprite3D, int>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.AnimatedSprite3D, int>, int>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.AnimatedSprite3D, int>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.AnimatedSprite3D, int>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.AnimatedSprite3D, int>>? OnFinally { get; init; }

    TweenDefinition<Godot.AnimatedSprite3D, int> ITweenDefinition<Godot.AnimatedSprite3D, int>.CreatePlayback()
    {
        var playback = new tweens.gd.AnimatedSprite3DFrameTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}
