// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Moritz Voss

// <auto-generated by csharp/tools/generate-structured.mjs />
#nullable enable
using tweens.gd;

namespace Tweens;

/// <summary>Reusable immutable PointLight2DTextureScale configuration. Each start creates independent playback.</summary>
public readonly record struct PointLight2DTextureScale : ITweenDefinition<Godot.PointLight2D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.PointLight2D, float> ITweenDefinition<Godot.PointLight2D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.PointLight2DTextureScaleTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable PointLight2DHeight configuration. Each start creates independent playback.</summary>
public readonly record struct PointLight2DHeight : ITweenDefinition<Godot.PointLight2D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.PointLight2D, float> ITweenDefinition<Godot.PointLight2D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.PointLight2DHeightTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable PointLight2DOffset configuration. Each start creates independent playback.</summary>
public readonly record struct PointLight2DOffset : ITweenDefinition<Godot.PointLight2D, Godot.Vector2>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Vector2? From { get; init; }
    public Godot.Vector2? To { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, Godot.Vector2>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, Godot.Vector2>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, Godot.Vector2>, Godot.Vector2>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, Godot.Vector2>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, Godot.Vector2>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, Godot.Vector2>>? OnFinally { get; init; }

    TweenDefinition<Godot.PointLight2D, Godot.Vector2> ITweenDefinition<Godot.PointLight2D, Godot.Vector2>.CreatePlayback()
    {
        var playback = new tweens.gd.PointLight2DOffsetTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable PointLight2DOffsetX configuration. Each start creates independent playback.</summary>
public readonly record struct PointLight2DOffsetX : ITweenDefinition<Godot.PointLight2D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.PointLight2D, float> ITweenDefinition<Godot.PointLight2D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.PointLight2DOffsetXTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable PointLight2DOffsetY configuration. Each start creates independent playback.</summary>
public readonly record struct PointLight2DOffsetY : ITweenDefinition<Godot.PointLight2D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.PointLight2D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.PointLight2D, float> ITweenDefinition<Godot.PointLight2D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.PointLight2DOffsetYTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Light2DShadowColor configuration. Each start creates independent playback.</summary>
public readonly record struct Light2DShadowColor : ITweenDefinition<Godot.Light2D, Godot.Color>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Color? From { get; init; }
    public Godot.Color? To { get; init; }
    public Action<TweenInstance<Godot.Light2D, Godot.Color>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Light2D, Godot.Color>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Light2D, Godot.Color>, Godot.Color>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Light2D, Godot.Color>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Light2D, Godot.Color>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Light2D, Godot.Color>>? OnFinally { get; init; }

    TweenDefinition<Godot.Light2D, Godot.Color> ITweenDefinition<Godot.Light2D, Godot.Color>.CreatePlayback()
    {
        var playback = new tweens.gd.Light2DShadowColorTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Light2DShadowColorAlpha configuration. Each start creates independent playback.</summary>
public readonly record struct Light2DShadowColorAlpha : ITweenDefinition<Godot.Light2D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Light2D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Light2D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Light2D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Light2D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Light2D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Light2D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Light2D, float> ITweenDefinition<Godot.Light2D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Light2DShadowColorAlphaTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Light3DLightTemperature configuration. Each start creates independent playback.</summary>
public readonly record struct Light3DLightTemperature : ITweenDefinition<Godot.Light3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Light3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Light3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Light3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Light3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Light3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Light3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Light3D, float> ITweenDefinition<Godot.Light3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Light3DLightTemperatureTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Light3DLightIndirectEnergy configuration. Each start creates independent playback.</summary>
public readonly record struct Light3DLightIndirectEnergy : ITweenDefinition<Godot.Light3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Light3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Light3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Light3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Light3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Light3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Light3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Light3D, float> ITweenDefinition<Godot.Light3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Light3DLightIndirectEnergyTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Light3DLightVolumetricFogEnergy configuration. Each start creates independent playback.</summary>
public readonly record struct Light3DLightVolumetricFogEnergy : ITweenDefinition<Godot.Light3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Light3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Light3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Light3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Light3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Light3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Light3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Light3D, float> ITweenDefinition<Godot.Light3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Light3DLightVolumetricFogEnergyTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Light3DShadowOpacity configuration. Each start creates independent playback.</summary>
public readonly record struct Light3DShadowOpacity : ITweenDefinition<Godot.Light3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Light3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Light3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Light3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Light3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Light3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Light3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Light3D, float> ITweenDefinition<Godot.Light3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Light3DShadowOpacityTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable OmniLight3DOmniAttenuation configuration. Each start creates independent playback.</summary>
public readonly record struct OmniLight3DOmniAttenuation : ITweenDefinition<Godot.OmniLight3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.OmniLight3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.OmniLight3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.OmniLight3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.OmniLight3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.OmniLight3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.OmniLight3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.OmniLight3D, float> ITweenDefinition<Godot.OmniLight3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.OmniLight3DOmniAttenuationTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable SpotLight3DSpotAttenuation configuration. Each start creates independent playback.</summary>
public readonly record struct SpotLight3DSpotAttenuation : ITweenDefinition<Godot.SpotLight3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.SpotLight3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.SpotLight3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.SpotLight3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.SpotLight3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.SpotLight3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.SpotLight3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.SpotLight3D, float> ITweenDefinition<Godot.SpotLight3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.SpotLight3DSpotAttenuationTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable SpotLight3DSpotAngleAttenuation configuration. Each start creates independent playback.</summary>
public readonly record struct SpotLight3DSpotAngleAttenuation : ITweenDefinition<Godot.SpotLight3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.SpotLight3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.SpotLight3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.SpotLight3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.SpotLight3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.SpotLight3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.SpotLight3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.SpotLight3D, float> ITweenDefinition<Godot.SpotLight3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.SpotLight3DSpotAngleAttenuationTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}
