// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Moritz Voss

// <auto-generated by csharp/tools/generate-structured.mjs />
#nullable enable
using tweens.gd;

namespace Tweens;

/// <summary>Reusable immutable Position2D configuration. Each start creates independent playback.</summary>
public readonly record struct Position2D : ITweenDefinition<Godot.Node2D, Godot.Vector2>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Vector2? From { get; init; }
    public Godot.Vector2? To { get; init; }
    public Action<TweenInstance<Godot.Node2D, Godot.Vector2>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Node2D, Godot.Vector2>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Node2D, Godot.Vector2>, Godot.Vector2>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Node2D, Godot.Vector2>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Node2D, Godot.Vector2>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Node2D, Godot.Vector2>>? OnFinally { get; init; }

    TweenDefinition<Godot.Node2D, Godot.Vector2> ITweenDefinition<Godot.Node2D, Godot.Vector2>.CreatePlayback()
    {
        var playback = new tweens.gd.Position2DTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Position2DX configuration. Each start creates independent playback.</summary>
public readonly record struct Position2DX : ITweenDefinition<Godot.Node2D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Node2D, float> ITweenDefinition<Godot.Node2D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Position2DXTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Position2DY configuration. Each start creates independent playback.</summary>
public readonly record struct Position2DY : ITweenDefinition<Godot.Node2D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Node2D, float> ITweenDefinition<Godot.Node2D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Position2DYTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable GlobalPosition2D configuration. Each start creates independent playback.</summary>
public readonly record struct GlobalPosition2D : ITweenDefinition<Godot.Node2D, Godot.Vector2>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Vector2? From { get; init; }
    public Godot.Vector2? To { get; init; }
    public Action<TweenInstance<Godot.Node2D, Godot.Vector2>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Node2D, Godot.Vector2>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Node2D, Godot.Vector2>, Godot.Vector2>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Node2D, Godot.Vector2>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Node2D, Godot.Vector2>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Node2D, Godot.Vector2>>? OnFinally { get; init; }

    TweenDefinition<Godot.Node2D, Godot.Vector2> ITweenDefinition<Godot.Node2D, Godot.Vector2>.CreatePlayback()
    {
        var playback = new tweens.gd.GlobalPosition2DTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable GlobalPosition2DX configuration. Each start creates independent playback.</summary>
public readonly record struct GlobalPosition2DX : ITweenDefinition<Godot.Node2D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Node2D, float> ITweenDefinition<Godot.Node2D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.GlobalPosition2DXTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable GlobalPosition2DY configuration. Each start creates independent playback.</summary>
public readonly record struct GlobalPosition2DY : ITweenDefinition<Godot.Node2D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Node2D, float> ITweenDefinition<Godot.Node2D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.GlobalPosition2DYTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Scale2D configuration. Each start creates independent playback.</summary>
public readonly record struct Scale2D : ITweenDefinition<Godot.Node2D, Godot.Vector2>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Vector2? From { get; init; }
    public Godot.Vector2? To { get; init; }
    public Action<TweenInstance<Godot.Node2D, Godot.Vector2>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Node2D, Godot.Vector2>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Node2D, Godot.Vector2>, Godot.Vector2>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Node2D, Godot.Vector2>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Node2D, Godot.Vector2>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Node2D, Godot.Vector2>>? OnFinally { get; init; }

    TweenDefinition<Godot.Node2D, Godot.Vector2> ITweenDefinition<Godot.Node2D, Godot.Vector2>.CreatePlayback()
    {
        var playback = new tweens.gd.Scale2DTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Scale2DX configuration. Each start creates independent playback.</summary>
public readonly record struct Scale2DX : ITweenDefinition<Godot.Node2D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Node2D, float> ITweenDefinition<Godot.Node2D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Scale2DXTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Scale2DY configuration. Each start creates independent playback.</summary>
public readonly record struct Scale2DY : ITweenDefinition<Godot.Node2D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Node2D, float> ITweenDefinition<Godot.Node2D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Scale2DYTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable Rotation2D configuration. Each start creates independent playback.</summary>
public readonly record struct Rotation2D : ITweenDefinition<Godot.Node2D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Node2D, float> ITweenDefinition<Godot.Node2D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.Rotation2DTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable GlobalRotation2D configuration. Each start creates independent playback.</summary>
public readonly record struct GlobalRotation2D : ITweenDefinition<Godot.Node2D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Node2D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Node2D, float> ITweenDefinition<Godot.Node2D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.GlobalRotation2DTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}
