// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Moritz Voss

// <auto-generated by csharp/tools/generate-structured.mjs />
#nullable enable
using tweens.gd;

namespace Tweens;

/// <summary>Reusable immutable Property configuration. Each start creates independent playback.</summary>
public readonly record struct Property<TTarget, TValue> : ITweenDefinition<TTarget, TValue>
    where TTarget : class where TValue : struct
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public TValue? From { get; init; }
    public TValue? To { get; init; }
    public Action<TweenInstance<TTarget, TValue>>? OnAdd { get; init; }
    public Action<TweenInstance<TTarget, TValue>>? OnStart { get; init; }
    public Action<TweenInstance<TTarget, TValue>, TValue>? OnUpdate { get; init; }
    public Action<TweenInstance<TTarget, TValue>>? OnEnd { get; init; }
    public Action<TweenInstance<TTarget, TValue>>? OnCancel { get; init; }
    public Action<TweenInstance<TTarget, TValue>>? OnFinally { get; init; }

    public Func<TTarget, TValue> Getter { get; init; }
    public Action<TTarget, TValue> Setter { get; init; }
    public Func<TValue, TValue, float, TValue> Interpolate { get; init; }

    public Property(Func<TTarget, TValue> getter, Action<TTarget, TValue> setter, Func<TValue, TValue, float, TValue> interpolate)
    {
        Getter = getter;
        Setter = setter;
        Interpolate = interpolate;
    }

    TweenDefinition<TTarget, TValue> ITweenDefinition<TTarget, TValue>.CreatePlayback()
    {
        var playback = new tweens.gd.PropertyTween<TTarget, TValue>(Getter, Setter, Interpolate)
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}
