// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Moritz Voss

// <auto-generated by csharp/tools/generate-structured.mjs />
#nullable enable
using tweens.gd;

namespace Tweens;

/// <summary>Reusable immutable AudioStreamPlayer2DPanningStrength configuration. Each start creates independent playback.</summary>
public readonly record struct AudioStreamPlayer2DPanningStrength : ITweenDefinition<Godot.AudioStreamPlayer2D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.AudioStreamPlayer2D, float> ITweenDefinition<Godot.AudioStreamPlayer2D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.AudioStreamPlayer2DPanningStrengthTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable AudioStreamPlayer2DMaxDistance configuration. Each start creates independent playback.</summary>
public readonly record struct AudioStreamPlayer2DMaxDistance : ITweenDefinition<Godot.AudioStreamPlayer2D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.AudioStreamPlayer2D, float> ITweenDefinition<Godot.AudioStreamPlayer2D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.AudioStreamPlayer2DMaxDistanceTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable AudioStreamPlayer3DPanningStrength configuration. Each start creates independent playback.</summary>
public readonly record struct AudioStreamPlayer3DPanningStrength : ITweenDefinition<Godot.AudioStreamPlayer3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.AudioStreamPlayer3D, float> ITweenDefinition<Godot.AudioStreamPlayer3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.AudioStreamPlayer3DPanningStrengthTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable AudioStreamPlayer3DMaxDistance configuration. Each start creates independent playback.</summary>
public readonly record struct AudioStreamPlayer3DMaxDistance : ITweenDefinition<Godot.AudioStreamPlayer3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.AudioStreamPlayer3D, float> ITweenDefinition<Godot.AudioStreamPlayer3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.AudioStreamPlayer3DMaxDistanceTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable AudioStreamPlayer2DAttenuation configuration. Each start creates independent playback.</summary>
public readonly record struct AudioStreamPlayer2DAttenuation : ITweenDefinition<Godot.AudioStreamPlayer2D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer2D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.AudioStreamPlayer2D, float> ITweenDefinition<Godot.AudioStreamPlayer2D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.AudioStreamPlayer2DAttenuationTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable AudioStreamPlayer3DUnitSize configuration. Each start creates independent playback.</summary>
public readonly record struct AudioStreamPlayer3DUnitSize : ITweenDefinition<Godot.AudioStreamPlayer3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.AudioStreamPlayer3D, float> ITweenDefinition<Godot.AudioStreamPlayer3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.AudioStreamPlayer3DUnitSizeTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable AudioStreamPlayer3DEmissionAngleDegrees configuration. Each start creates independent playback.</summary>
public readonly record struct AudioStreamPlayer3DEmissionAngleDegrees : ITweenDefinition<Godot.AudioStreamPlayer3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.AudioStreamPlayer3D, float> ITweenDefinition<Godot.AudioStreamPlayer3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.AudioStreamPlayer3DEmissionAngleDegreesTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable AudioStreamPlayer3DEmissionAngleFilterAttenuationDb configuration. Each start creates independent playback.</summary>
public readonly record struct AudioStreamPlayer3DEmissionAngleFilterAttenuationDb : ITweenDefinition<Godot.AudioStreamPlayer3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.AudioStreamPlayer3D, float> ITweenDefinition<Godot.AudioStreamPlayer3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.AudioStreamPlayer3DEmissionAngleFilterAttenuationDbTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable AudioStreamPlayer3DAttenuationFilterCutoffHz configuration. Each start creates independent playback.</summary>
public readonly record struct AudioStreamPlayer3DAttenuationFilterCutoffHz : ITweenDefinition<Godot.AudioStreamPlayer3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.AudioStreamPlayer3D, float> ITweenDefinition<Godot.AudioStreamPlayer3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.AudioStreamPlayer3DAttenuationFilterCutoffHzTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable AudioStreamPlayer3DAttenuationFilterDb configuration. Each start creates independent playback.</summary>
public readonly record struct AudioStreamPlayer3DAttenuationFilterDb : ITweenDefinition<Godot.AudioStreamPlayer3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.AudioStreamPlayer3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.AudioStreamPlayer3D, float> ITweenDefinition<Godot.AudioStreamPlayer3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.AudioStreamPlayer3DAttenuationFilterDbTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}
