// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Moritz Voss

// <auto-generated by csharp/tools/generate-structured.mjs />
#nullable enable
using tweens.gd;

namespace Tweens;

/// <summary>Reusable immutable ColorRectColor configuration. Each start creates independent playback.</summary>
public readonly record struct ColorRectColor : ITweenDefinition<Godot.ColorRect, Godot.Color>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Color? From { get; init; }
    public Godot.Color? To { get; init; }
    public Action<TweenInstance<Godot.ColorRect, Godot.Color>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.ColorRect, Godot.Color>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.ColorRect, Godot.Color>, Godot.Color>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.ColorRect, Godot.Color>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.ColorRect, Godot.Color>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.ColorRect, Godot.Color>>? OnFinally { get; init; }

    TweenDefinition<Godot.ColorRect, Godot.Color> ITweenDefinition<Godot.ColorRect, Godot.Color>.CreatePlayback()
    {
        var playback = new tweens.gd.ColorRectColorTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable ColorRectColorAlpha configuration. Each start creates independent playback.</summary>
public readonly record struct ColorRectColorAlpha : ITweenDefinition<Godot.ColorRect, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.ColorRect, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.ColorRect, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.ColorRect, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.ColorRect, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.ColorRect, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.ColorRect, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.ColorRect, float> ITweenDefinition<Godot.ColorRect, float>.CreatePlayback()
    {
        var playback = new tweens.gd.ColorRectColorAlphaTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable LabelVisibleRatio configuration. Each start creates independent playback.</summary>
public readonly record struct LabelVisibleRatio : ITweenDefinition<Godot.Label, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Label, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Label, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Label, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Label, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Label, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Label, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Label, float> ITweenDefinition<Godot.Label, float>.CreatePlayback()
    {
        var playback = new tweens.gd.LabelVisibleRatioTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable RichTextLabelVisibleRatio configuration. Each start creates independent playback.</summary>
public readonly record struct RichTextLabelVisibleRatio : ITweenDefinition<Godot.RichTextLabel, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.RichTextLabel, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.RichTextLabel, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.RichTextLabel, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.RichTextLabel, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.RichTextLabel, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.RichTextLabel, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.RichTextLabel, float> ITweenDefinition<Godot.RichTextLabel, float>.CreatePlayback()
    {
        var playback = new tweens.gd.RichTextLabelVisibleRatioTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable TextureProgressBarTintUnder configuration. Each start creates independent playback.</summary>
public readonly record struct TextureProgressBarTintUnder : ITweenDefinition<Godot.TextureProgressBar, Godot.Color>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Color? From { get; init; }
    public Godot.Color? To { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Color>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Color>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Color>, Godot.Color>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Color>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Color>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Color>>? OnFinally { get; init; }

    TweenDefinition<Godot.TextureProgressBar, Godot.Color> ITweenDefinition<Godot.TextureProgressBar, Godot.Color>.CreatePlayback()
    {
        var playback = new tweens.gd.TextureProgressBarTintUnderTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable TextureProgressBarTintUnderAlpha configuration. Each start creates independent playback.</summary>
public readonly record struct TextureProgressBarTintUnderAlpha : ITweenDefinition<Godot.TextureProgressBar, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.TextureProgressBar, float> ITweenDefinition<Godot.TextureProgressBar, float>.CreatePlayback()
    {
        var playback = new tweens.gd.TextureProgressBarTintUnderAlphaTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable TextureProgressBarTintOver configuration. Each start creates independent playback.</summary>
public readonly record struct TextureProgressBarTintOver : ITweenDefinition<Godot.TextureProgressBar, Godot.Color>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Color? From { get; init; }
    public Godot.Color? To { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Color>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Color>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Color>, Godot.Color>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Color>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Color>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Color>>? OnFinally { get; init; }

    TweenDefinition<Godot.TextureProgressBar, Godot.Color> ITweenDefinition<Godot.TextureProgressBar, Godot.Color>.CreatePlayback()
    {
        var playback = new tweens.gd.TextureProgressBarTintOverTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable TextureProgressBarTintOverAlpha configuration. Each start creates independent playback.</summary>
public readonly record struct TextureProgressBarTintOverAlpha : ITweenDefinition<Godot.TextureProgressBar, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.TextureProgressBar, float> ITweenDefinition<Godot.TextureProgressBar, float>.CreatePlayback()
    {
        var playback = new tweens.gd.TextureProgressBarTintOverAlphaTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable TextureProgressBarTintProgress configuration. Each start creates independent playback.</summary>
public readonly record struct TextureProgressBarTintProgress : ITweenDefinition<Godot.TextureProgressBar, Godot.Color>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Color? From { get; init; }
    public Godot.Color? To { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Color>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Color>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Color>, Godot.Color>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Color>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Color>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Color>>? OnFinally { get; init; }

    TweenDefinition<Godot.TextureProgressBar, Godot.Color> ITweenDefinition<Godot.TextureProgressBar, Godot.Color>.CreatePlayback()
    {
        var playback = new tweens.gd.TextureProgressBarTintProgressTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable TextureProgressBarTintProgressAlpha configuration. Each start creates independent playback.</summary>
public readonly record struct TextureProgressBarTintProgressAlpha : ITweenDefinition<Godot.TextureProgressBar, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.TextureProgressBar, float> ITweenDefinition<Godot.TextureProgressBar, float>.CreatePlayback()
    {
        var playback = new tweens.gd.TextureProgressBarTintProgressAlphaTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable TextureProgressBarRadialInitialAngle configuration. Each start creates independent playback.</summary>
public readonly record struct TextureProgressBarRadialInitialAngle : ITweenDefinition<Godot.TextureProgressBar, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.TextureProgressBar, float> ITweenDefinition<Godot.TextureProgressBar, float>.CreatePlayback()
    {
        var playback = new tweens.gd.TextureProgressBarRadialInitialAngleTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable TextureProgressBarRadialFillDegrees configuration. Each start creates independent playback.</summary>
public readonly record struct TextureProgressBarRadialFillDegrees : ITweenDefinition<Godot.TextureProgressBar, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.TextureProgressBar, float> ITweenDefinition<Godot.TextureProgressBar, float>.CreatePlayback()
    {
        var playback = new tweens.gd.TextureProgressBarRadialFillDegreesTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable TextureProgressBarRadialCenterOffset configuration. Each start creates independent playback.</summary>
public readonly record struct TextureProgressBarRadialCenterOffset : ITweenDefinition<Godot.TextureProgressBar, Godot.Vector2>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Vector2? From { get; init; }
    public Godot.Vector2? To { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Vector2>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Vector2>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Vector2>, Godot.Vector2>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Vector2>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Vector2>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Vector2>>? OnFinally { get; init; }

    TweenDefinition<Godot.TextureProgressBar, Godot.Vector2> ITweenDefinition<Godot.TextureProgressBar, Godot.Vector2>.CreatePlayback()
    {
        var playback = new tweens.gd.TextureProgressBarRadialCenterOffsetTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable TextureProgressBarRadialCenterOffsetX configuration. Each start creates independent playback.</summary>
public readonly record struct TextureProgressBarRadialCenterOffsetX : ITweenDefinition<Godot.TextureProgressBar, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.TextureProgressBar, float> ITweenDefinition<Godot.TextureProgressBar, float>.CreatePlayback()
    {
        var playback = new tweens.gd.TextureProgressBarRadialCenterOffsetXTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable TextureProgressBarRadialCenterOffsetY configuration. Each start creates independent playback.</summary>
public readonly record struct TextureProgressBarRadialCenterOffsetY : ITweenDefinition<Godot.TextureProgressBar, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.TextureProgressBar, float> ITweenDefinition<Godot.TextureProgressBar, float>.CreatePlayback()
    {
        var playback = new tweens.gd.TextureProgressBarRadialCenterOffsetYTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable TextureProgressBarTextureProgressOffset configuration. Each start creates independent playback.</summary>
public readonly record struct TextureProgressBarTextureProgressOffset : ITweenDefinition<Godot.TextureProgressBar, Godot.Vector2>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Vector2? From { get; init; }
    public Godot.Vector2? To { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Vector2>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Vector2>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Vector2>, Godot.Vector2>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Vector2>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Vector2>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, Godot.Vector2>>? OnFinally { get; init; }

    TweenDefinition<Godot.TextureProgressBar, Godot.Vector2> ITweenDefinition<Godot.TextureProgressBar, Godot.Vector2>.CreatePlayback()
    {
        var playback = new tweens.gd.TextureProgressBarTextureProgressOffsetTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable TextureProgressBarTextureProgressOffsetX configuration. Each start creates independent playback.</summary>
public readonly record struct TextureProgressBarTextureProgressOffsetX : ITweenDefinition<Godot.TextureProgressBar, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.TextureProgressBar, float> ITweenDefinition<Godot.TextureProgressBar, float>.CreatePlayback()
    {
        var playback = new tweens.gd.TextureProgressBarTextureProgressOffsetXTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable TextureProgressBarTextureProgressOffsetY configuration. Each start creates independent playback.</summary>
public readonly record struct TextureProgressBarTextureProgressOffsetY : ITweenDefinition<Godot.TextureProgressBar, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.TextureProgressBar, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.TextureProgressBar, float> ITweenDefinition<Godot.TextureProgressBar, float>.CreatePlayback()
    {
        var playback = new tweens.gd.TextureProgressBarTextureProgressOffsetYTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}
