// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2026 Moritz Voss

// <auto-generated by csharp/tools/generate-structured.mjs />
#nullable enable
using tweens.gd;

namespace Tweens;

/// <summary>Reusable immutable SpringArm3DSpringLength configuration. Each start creates independent playback.</summary>
public readonly record struct SpringArm3DSpringLength : ITweenDefinition<Godot.SpringArm3D, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.SpringArm3D, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.SpringArm3D, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.SpringArm3D, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.SpringArm3D, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.SpringArm3D, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.SpringArm3D, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.SpringArm3D, float> ITweenDefinition<Godot.SpringArm3D, float>.CreatePlayback()
    {
        var playback = new tweens.gd.SpringArm3DSpringLengthTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable DecalModulate configuration. Each start creates independent playback.</summary>
public readonly record struct DecalModulate : ITweenDefinition<Godot.Decal, Godot.Color>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Color? From { get; init; }
    public Godot.Color? To { get; init; }
    public Action<TweenInstance<Godot.Decal, Godot.Color>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Decal, Godot.Color>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Decal, Godot.Color>, Godot.Color>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Decal, Godot.Color>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Decal, Godot.Color>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Decal, Godot.Color>>? OnFinally { get; init; }

    TweenDefinition<Godot.Decal, Godot.Color> ITweenDefinition<Godot.Decal, Godot.Color>.CreatePlayback()
    {
        var playback = new tweens.gd.DecalModulateTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable DecalModulateAlpha configuration. Each start creates independent playback.</summary>
public readonly record struct DecalModulateAlpha : ITweenDefinition<Godot.Decal, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Decal, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Decal, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Decal, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Decal, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Decal, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Decal, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Decal, float> ITweenDefinition<Godot.Decal, float>.CreatePlayback()
    {
        var playback = new tweens.gd.DecalModulateAlphaTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable DecalSize configuration. Each start creates independent playback.</summary>
public readonly record struct DecalSize : ITweenDefinition<Godot.Decal, Godot.Vector3>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Vector3? From { get; init; }
    public Godot.Vector3? To { get; init; }
    public Action<TweenInstance<Godot.Decal, Godot.Vector3>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Decal, Godot.Vector3>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Decal, Godot.Vector3>, Godot.Vector3>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Decal, Godot.Vector3>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Decal, Godot.Vector3>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Decal, Godot.Vector3>>? OnFinally { get; init; }

    TweenDefinition<Godot.Decal, Godot.Vector3> ITweenDefinition<Godot.Decal, Godot.Vector3>.CreatePlayback()
    {
        var playback = new tweens.gd.DecalSizeTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable DecalSizeX configuration. Each start creates independent playback.</summary>
public readonly record struct DecalSizeX : ITweenDefinition<Godot.Decal, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Decal, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Decal, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Decal, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Decal, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Decal, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Decal, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Decal, float> ITweenDefinition<Godot.Decal, float>.CreatePlayback()
    {
        var playback = new tweens.gd.DecalSizeXTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable DecalSizeY configuration. Each start creates independent playback.</summary>
public readonly record struct DecalSizeY : ITweenDefinition<Godot.Decal, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Decal, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Decal, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Decal, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Decal, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Decal, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Decal, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Decal, float> ITweenDefinition<Godot.Decal, float>.CreatePlayback()
    {
        var playback = new tweens.gd.DecalSizeYTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable DecalSizeZ configuration. Each start creates independent playback.</summary>
public readonly record struct DecalSizeZ : ITweenDefinition<Godot.Decal, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Decal, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Decal, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Decal, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Decal, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Decal, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Decal, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Decal, float> ITweenDefinition<Godot.Decal, float>.CreatePlayback()
    {
        var playback = new tweens.gd.DecalSizeZTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable DecalEmissionEnergy configuration. Each start creates independent playback.</summary>
public readonly record struct DecalEmissionEnergy : ITweenDefinition<Godot.Decal, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.Decal, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.Decal, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.Decal, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.Decal, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.Decal, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.Decal, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.Decal, float> ITweenDefinition<Godot.Decal, float>.CreatePlayback()
    {
        var playback = new tweens.gd.DecalEmissionEnergyTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable FogVolumeSize configuration. Each start creates independent playback.</summary>
public readonly record struct FogVolumeSize : ITweenDefinition<Godot.FogVolume, Godot.Vector3>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public Godot.Vector3? From { get; init; }
    public Godot.Vector3? To { get; init; }
    public Action<TweenInstance<Godot.FogVolume, Godot.Vector3>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.FogVolume, Godot.Vector3>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.FogVolume, Godot.Vector3>, Godot.Vector3>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.FogVolume, Godot.Vector3>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.FogVolume, Godot.Vector3>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.FogVolume, Godot.Vector3>>? OnFinally { get; init; }

    TweenDefinition<Godot.FogVolume, Godot.Vector3> ITweenDefinition<Godot.FogVolume, Godot.Vector3>.CreatePlayback()
    {
        var playback = new tweens.gd.FogVolumeSizeTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable FogVolumeSizeX configuration. Each start creates independent playback.</summary>
public readonly record struct FogVolumeSizeX : ITweenDefinition<Godot.FogVolume, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.FogVolume, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.FogVolume, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.FogVolume, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.FogVolume, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.FogVolume, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.FogVolume, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.FogVolume, float> ITweenDefinition<Godot.FogVolume, float>.CreatePlayback()
    {
        var playback = new tweens.gd.FogVolumeSizeXTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable FogVolumeSizeY configuration. Each start creates independent playback.</summary>
public readonly record struct FogVolumeSizeY : ITweenDefinition<Godot.FogVolume, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.FogVolume, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.FogVolume, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.FogVolume, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.FogVolume, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.FogVolume, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.FogVolume, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.FogVolume, float> ITweenDefinition<Godot.FogVolume, float>.CreatePlayback()
    {
        var playback = new tweens.gd.FogVolumeSizeYTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}

/// <summary>Reusable immutable FogVolumeSizeZ configuration. Each start creates independent playback.</summary>
public readonly record struct FogVolumeSizeZ : ITweenDefinition<Godot.FogVolume, float>
{
    public TweenOptions Options { get; init; }
    public double Duration { get => Options.Duration; init => Options = Options with { Duration = value }; }
    public double Delay { get => Options.Delay; init => Options = Options with { Delay = value }; }
    public double PingPongInterval { get => Options.PingPongInterval; init => Options = Options with { PingPongInterval = value }; }
    public double RepeatInterval { get => Options.RepeatInterval; init => Options = Options with { RepeatInterval = value }; }
    public double Offset { get => Options.Offset; init => Options = Options with { Offset = value }; }
    public int Repeats { get => Options.Repeats; init => Options = Options with { Repeats = value }; }
    public bool UsePingPong { get => Options.UsePingPong; init => Options = Options with { UsePingPong = value }; }
    public bool UseUnscaledTime { get => Options.UseUnscaledTime; init => Options = Options with { UseUnscaledTime = value }; }
    public FillMode Fill { get => Options.Fill; init => Options = Options with { Fill = value }; }
    public EaseType Ease { get => Options.Ease; init => Options = Options with { Ease = value }; }
    public Func<float, float>? EaseFunction { get => Options.EaseFunction; init => Options = Options with { EaseFunction = value }; }
    public Godot.Curve? Curve { get => Options.Curve; init => Options = Options with { Curve = value }; }
    public TweenProcessMode ProcessMode { get => Options.ProcessMode; init => Options = Options with { ProcessMode = value }; }
    public TweenPauseMode PauseMode { get => Options.PauseMode; init => Options = Options with { PauseMode = value }; }
    public bool SuppressCallbacksWhenTargetInvalid { get => Options.SuppressCallbacksWhenTargetInvalid; init => Options = Options with { SuppressCallbacksWhenTargetInvalid = value }; }

    public float? From { get; init; }
    public float? To { get; init; }
    public Action<TweenInstance<Godot.FogVolume, float>>? OnAdd { get; init; }
    public Action<TweenInstance<Godot.FogVolume, float>>? OnStart { get; init; }
    public Action<TweenInstance<Godot.FogVolume, float>, float>? OnUpdate { get; init; }
    public Action<TweenInstance<Godot.FogVolume, float>>? OnEnd { get; init; }
    public Action<TweenInstance<Godot.FogVolume, float>>? OnCancel { get; init; }
    public Action<TweenInstance<Godot.FogVolume, float>>? OnFinally { get; init; }

    TweenDefinition<Godot.FogVolume, float> ITweenDefinition<Godot.FogVolume, float>.CreatePlayback()
    {
        var playback = new tweens.gd.FogVolumeSizeZTween
        {
            From = From,
            To = To,
            OnAdd = OnAdd,
            OnStart = OnStart,
            OnUpdate = OnUpdate,
            OnEnd = OnEnd,
            OnCancel = OnCancel,
            OnFinally = OnFinally,
        };
        Options.CopyTo(playback);
        return playback;
    }
}
